# Setup
title:               φ (phi)
tagline:             'Philosophie, sciences, numérique et culture libre.'
description:         "Blog d'un étudiant en master de philosophie analytique."
url:                 http://valentinlageard.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Valentin Lageard
  url:               https://twitter.com/valentinlageard
  email:             valentin.lageard@gmail.com

# Custom vars
version:             1.0.0
