# Setup
title:               Lo-phi
tagline:             'Philosophie, sciences, numérique et culture libre.'
description:         "Blog de Valentin Lageard, étudiant en master de philosophie."
url:                 http://lophi.ramdam.space
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Valentin Lageard
  url:               https://twitter.com/valentinlageard
  email:             valentin.lageard@gmail.com

# Custom vars
version:             1.0.0
